### ISSUE TITLE
因此支持智能合约的区块链需要恰当的机制来限制资源使用?

### ISSUE THREAD

**Issue by cristicmf** [cryptape/cita-whitepaper#1]
因此支持智能合约的区块链需要恰当的机制来限制资源使用?
能不能详细的解释一下呢

**Comment by janx** [comment]
如果对计算和存储等资源使用不做限制，攻击者可以构造恶意交易对网络发起DoS攻击，原因是所有节点都会花费过多的资源处理这个恶意交易。

**Comment by cristicmf** [comment]
你们做了哪些限制呢？
